- name: Install Packages
  hosts: servers
  become: yes

  vars:
    packages_to_install:
    - tree
    - zip
    - unzip
    - jq
    - wget
    - apache2

  tasks:
    - name: Install Packages
      apt:
        name: "{{item}}"
        state: present
      loop: "{{ packages_to_install }}"

    - name: Show message
      loop: "{{ packages_to_install }}"
      debug:
        msg: "Installing {{item}}"
      
    
  
