- name: Show Secrets
  hosts: servers
  become: yes

  vars_files: 
    - secrets.yml

  tasks:
    - name: Show Passwords
      debug:
        msg: "My Password is {{ password }}"
      no_log: true

    - name : Show API key
      debug: 
        msg: "My API kye is {{ api_key }}"
      no_log: true
    
    - name: Show username
      debug:
        msg: "My username is {{ username }}"
      no_log: true